processed_logs = [{'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: STARTUP_MSG:',
                   'timestamp': '2021-12-16T05:15:27.989000', 'level': 'INFO',
                   'template': '<*> <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'param_1': '# STARTUP_MSG:', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: registered UNIX signal handlers for [TERM, HUP, INT]',
                   'timestamp': '2021-12-16T05:15:35.447000', 'level': 'INFO',
                   'template': '<*> registered UNIX signal handlers for [TERM, HUP, INT]',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.checker.ThrottledAsyncChecker: Scheduling a check for [DISK]file:/tmp/hadoop-hduser/dfs/data',
                   'timestamp': '2021-12-16T05:15:36.193000', 'level': 'INFO',
                   'template': '<*> Scheduling a check for <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.checker.ThrottledAsyncChecker:',
                   'param_1': '# [DISK]file:/tmp/hadoop-hduser/dfs/data',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.metrics2.impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties',
                   'timestamp': '2021-12-16T05:15:36.939000', 'level': 'INFO',
                   'template': '<*> Loaded properties from <*>',
                   'param_0': '# org.apache.hadoop.metrics2.impl.MetricsConfig:',
                   'param_1': '# hadoop-metrics2.properties',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: STARTUP_MSG:',
                   'timestamp': '2021-12-16T05:15:27.989000', 'level': 'INFO',
                   'template': '<*> <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'param_1': '# STARTUP_MSG:', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: registered UNIX signal handlers for [TERM, HUP, INT]',
                   'timestamp': '2021-12-16T05:15:35.447000', 'level': 'INFO',
                   'template': '<*> registered UNIX signal handlers for [TERM, HUP, INT]',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.checker.ThrottledAsyncChecker: Scheduling a check for [DISK]file:/tmp/hadoop-hduser/dfs/data',
                   'timestamp': '2021-12-16T05:15:36.193000', 'level': 'INFO',
                   'template': '<*> Scheduling a check for <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.checker.ThrottledAsyncChecker:',
                   'param_1': '# [DISK]file:/tmp/hadoop-hduser/dfs/data',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.metrics2.impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties',
                   'timestamp': '2021-12-16T05:15:36.939000', 'level': 'INFO',
                   'template': '<*> Loaded properties from <*>',
                   'param_0': '# org.apache.hadoop.metrics2.impl.MetricsConfig:',
                   'param_1': '# hadoop-metrics2.properties',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).',
                   'timestamp': '2021-12-16T05:15:37.684000', 'level': 'INFO',
                   'template': '<*> Scheduled Metric snapshot period at <*> <*>',
                   'param_0': '# org.apache.hadoop.metrics2.impl.MetricsSystemImpl:',
                   'param_1': '# 10', 'param_2': '# second(s).',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.metrics2.impl.MetricsSystemImpl: DataNode metrics system started',
                   'timestamp': '2021-12-16T05:15:38.430000', 'level': 'INFO',
                   'template': '<*> DataNode metrics system started',
                   'param_0': '# org.apache.hadoop.metrics2.impl.MetricsSystemImpl:',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.common.Util: dfs.datanode.fileio.profiling.sampling.percentage set to 0. Disabling file IO profiling',
                   'timestamp': '2021-12-16T05:15:39.176000', 'level': 'INFO',
                   'template': '<*> <*> set to <*> Disabling file IO profiling',
                   'param_0': '# org.apache.hadoop.hdfs.server.common.Util:',
                   'param_1': '# dfs.datanode.fileio.profiling.sampling.percentage',
                   'param_2': '# 0.', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.BlockScanner: Initialized block scanner with targetBytesPerSec 1048576',
                   'timestamp': '2021-12-16T05:15:39.922000', 'level': 'INFO',
                   'template': '<*> Initialized block scanner with targetBytesPerSec <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.BlockScanner:',
                   'param_1': '# 1048576', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: Configured hostname is hadoop',
                   'timestamp': '2021-12-16T05:15:40.668000', 'level': 'INFO',
                   'template': '<*> Configured hostname is hadoop',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.common.Util: dfs.datanode.fileio.profiling.sampling.percentage set to 0. Disabling file IO profiling',
                   'timestamp': '2021-12-16T05:15:41.413000', 'level': 'INFO',
                   'template': '<*> <*> set to <*> Disabling file IO profiling',
                   'param_0': '# org.apache.hadoop.hdfs.server.common.Util:',
                   'param_1': '# dfs.datanode.fileio.profiling.sampling.percentage',
                   'param_2': '# 0.', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: Starting DataNode with maxLockedMemory = 0',
                   'timestamp': '2021-12-16T05:15:42.159000', 'level': 'INFO',
                   'template': '<*> Starting DataNode with maxLockedMemory = <*>',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: Opened streaming server at /0.0.0.0:9866',
                   'timestamp': '2021-12-16T05:15:42.905000', 'level': 'INFO',
                   'template': '<*> Opened streaming server at <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'param_1': '# /0.0.0.0:9866', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: Balancing bandwidth is 104857600 bytes/s',
                   'timestamp': '2021-12-16T05:15:43.651000', 'level': 'INFO',
                   'template': '<*> Balancing bandwidth is <*> <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'param_1': '# 104857600', 'param_2': '# bytes/s',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.hdfs.server.datanode.DataNode: Number threads for balancing is 100',
                   'timestamp': '2021-12-16T05:15:44.397000', 'level': 'INFO',
                   'template': '<*> Number threads for balancing is <*>',
                   'param_0': '# org.apache.hadoop.hdfs.server.datanode.DataNode:',
                   'param_1': '# 100', 'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.eclipse.jetty.util.log: Logging initialized @1124ms to org.eclipse.jetty.util.log.Slf4jLog',
                   'timestamp': '2021-12-16T05:15:45.142000', 'level': 'INFO',
                   'template': '<*> Logging initialized <*> to <*>',
                   'param_0': '# org.eclipse.jetty.util.log:',
                   'param_1': '# @1124ms',
                   'param_2': '# org.eclipse.jetty.util.log.Slf4jLog',
                   'prediction': 1},
                  {'id': None, 'tags': {'default': 'fileName'},
                   'message': 'org.apache.hadoop.http.HttpRequestLog: Http request log for http.requests.datanode is not defined',
                   'timestamp': '2021-12-16T05:15:46.634000', 'level': 'INFO',
                   'template': '<*> Http request log for <*> is not defined',
                   'param_0': '# org.apache.hadoop.http.HttpRequestLog:',
                   'param_1': '# http.requests.datanode', 'prediction': 1}]

agg_results = [{'log_levels': {'INFO': 20}, 'prediction': 20, 'count': 20,
                'timestamp': '2021-12-16T05:15:00.000000'}]
