connectors : {
source : {
         connection : 'zeromq',
         classname : 'ZeroMQRepSource',
         params : {
         endpoint : 'tcp://0.0.0.0:5555'
         }
         }
}
services : {
           database : {
           classname : 'PostgresDBConnection',
           connection : `$DATABASE|postgres`
           },
           elasticsearch_admin : {
           classname : 'ElasticSearchAdmin',
           connection : 'elasticsearch'
           }
}
}